# Step 1: Use an official Node.js image as the base image
FROM node:18-alpine

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Install dependencies
# Copy the package.json and package-lock.json to the working directory
COPY client/. package*.json ./

# Install the dependencies inside the container
RUN npm install --frozen-lockfile

# Step 4: Copy the rest of the application code into the container
COPY client/. .

# Step 5: Build the Next.js application
RUN npm run build

# Step 6: Expose the port Next.js will run on
EXPOSE 3000 

# Step 7: Start the Next.js application
CMD ["npm", "start"]
