FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    unzip \
    git \
    && docker-php-ext-install zip \
    && a2enmod rewrite

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


COPY . /var/www/html

WORKDIR /var/www/html
# COPY apache2.conf /etc/apache2/apache2.conf
# COPY 000-default.conf /etc/apache2/sites-enabled/000-default.conf
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN composer install
RUN chown -R www-data:www-data /var/www/html/storage
RUN chmod -R 777 /var/www/html/storage

EXPOSE 80

# Start PHP-FPM
CMD ["php-fpm"]
