import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import { AuthProvider } from "@/context/AuthContext";
import { CartProvider } from "@/context/CartContext";
import Category from "@/components/Category";
import localFont from 'next/font/local'
import Footer from "@/components/Footer";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { LoadingProvider, useLoading } from '../context/LoadingContext';
import Spinner from "@/components/Spinner";
import { TitleProvider } from "@/context/TitleContext";
// import { ThemeProvider } from "next-themes";
import { ThemeProvider } from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: '--font-poppins-sans',
  subsets: ["latin"],
  weight: '400'
})

const bogleFont = localFont({
  src: [
    { path: '../../public/fonts/bogle/BogleWeb-Regular.woff2', weight: '400', style: 'normal' },
    // { path: '../../public/fonts/bogle/BOGLEBOLD.OTF', weight: '700', style: 'normal' },
  ],
  variable: '--font-bogle',
});

export const metadata = {
  title: "MyStore",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png', 
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${bogleFont.variable}   antialiased `}
        >
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
                />
        <TitleProvider>
        <LoadingProvider>
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              >
              <main className=" bg-white dark:bg-black">
                {children}
              </main>
            </ThemeProvider>
          </AuthProvider>
        </LoadingProvider>
        </TitleProvider>
      </body>
    </html>
  );
}